name: spectrum
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - blosc=1.21.6=hf7d4471_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - c-blosc2=2.17.1=h4257ac4_0
  - ca-certificates=2025.11.4=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.1=py313hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.16=py313hbdd6827_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.60.1=py313hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - gettext=0.21.0=hedfda30_2
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - hdf5=1.14.5=h2b7332f_2
  - icu=73.1=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=h06a4308_1171
  - ipykernel=7.1.0=pyha191276_0
  - ipython=9.7.0=pyh53cf698_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - joblib=1.5.2=py313h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.9.1=pyhc90fa1f_0
  - kiwisolver=1.4.8=py313h6a678d5_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libcups=2.4.2=h252cb56_2
  - libcurl=8.16.0=heebcbe5_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.4=h77a78f3_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm15=15.0.7=he89c38a_4
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.57.0=h2d74bed_0
  - libopengl=1.7.0=h5eee18b_2
  - libopenjpeg=2.5.4=hee96239_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.50=h2ed474d_0
  - libpq=17.6=ha51bf15_0
  - libsodium=1.0.20=heac8642_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - lzo=2.10=h7b6447c_2
  - matplotlib=3.10.6=py313h06a4308_0
  - matplotlib-base=3.10.6=py313h4948728_0
  - matplotlib-inline=0.2.1=pyhd8ed1ab_0
  - mesalib=25.1.5=h31e3550_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py313hacdc0fc_0
  - mkl_fft=2.1.1=py313h57662e1_0
  - mkl_random=1.3.0=py313h23c847b_0
  - mysql-common=9.3.0=h0021b1a_3
  - mysql-libs=9.3.0=h797a5cd_3
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.14.1=py313h41d4191_0
  - openjpeg=2.5.4=h4e0627c_1
  - openldap=2.6.10=he9288cc_1
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=pyh29332c3_1
  - parso=0.8.5=pyhcf101f3_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pillow=11.3.0=py313hb1c3d2d_0
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.0.0=py313hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py-cpuinfo=9.0.0=py313h06a4308_0
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyparsing=3.2.0=py313h06a4308_0
  - pyqt=6.9.1=py313hc79087c_0
  - pyqt6-sip=13.10.2=py313hee96239_0
  - pytables=3.10.2=py313hc48ae32_2
  - python=3.13.9=h7e8bc2b_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.13=1_cp313
  - pyzmq=27.1.0=py313hcf8288c_1
  - qtbase=6.9.2=hd13baf8_4
  - qtdeclarative=6.9.2=h55666de_1
  - qtsvg=6.9.2=h75a08ff_1
  - qttools=6.9.2=hc856bc8_1
  - qtwayland=6.9.2=h9f1b7ec_1
  - qtwebchannel=6.9.2=hbdd6827_1
  - qtwebsockets=6.9.2=hbdd6827_1
  - readline=8.3=hc2a1206_0
  - scikit-learn=1.7.2=py313h23c847b_0
  - scipy=1.16.3=py313h33bc11c_0
  - setuptools=80.9.0=py313h06a4308_0
  - sip=6.12.0=py313h7934f7d_0
  - six=1.17.0=pyhe01879c_1
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - threadpoolctl=3.5.0=py313h7040dfc_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.1=py313h5eee18b_0
  - tqdm=4.67.1=py313h7040dfc_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing-extensions=4.15.0=py313h06a4308_0
  - typing_extensions=4.15.0=py313h06a4308_0
  - wayland=1.24.0=hdac8c69_0
  - wcwidth=0.2.14=pyhd8ed1ab_0
  - wheel=0.45.1=py313h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - zlib-ng=2.0.7=h5eee18b_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - filelock==3.20.0
      - fsspec==2025.10.0
      - jinja2==3.1.6
      - markupsafe==3.0.3
      - mpmath==1.3.0
      - networkx==3.5
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - pandas==2.3.3
      - prts==1.0.0.3
      - pytz==2025.2
      - sympy==1.14.0
      - torch==2.9.0
      - triton==3.5.0
      - tzdata==2025.2
prefix: /home/smore/anaconda3/envs/spectrum
